// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RelativeTimeFormatter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("target_date")]
        public DateTimeOffset TargetDate { get; set; }

        [JsonProperty("reference_date")]
        public DateTimeOffset ReferenceDate { get; set; }

        [JsonProperty("relative_time")]
        public string RelativeTime { get; set; }

        [JsonProperty("is_past")]
        public bool IsPast { get; set; }

        [JsonProperty("is_future")]
        public bool IsFuture { get; set; }

        [JsonProperty("difference_ms")]
        public long DifferenceMs { get; set; }

        [JsonProperty("primary_unit")]
        public string PrimaryUnit { get; set; }

        [JsonProperty("primary_value")]
        public long PrimaryValue { get; set; }

        [JsonProperty("all_units")]
        public AllUnits AllUnits { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }
    }

    public partial class AllUnits
    {
        [JsonProperty("years")]
        public long Years { get; set; }

        [JsonProperty("months")]
        public long Months { get; set; }

        [JsonProperty("weeks")]
        public long Weeks { get; set; }

        [JsonProperty("days")]
        public long Days { get; set; }

        [JsonProperty("hours")]
        public long Hours { get; set; }

        [JsonProperty("minutes")]
        public long Minutes { get; set; }

        [JsonProperty("seconds")]
        public long Seconds { get; set; }

        [JsonProperty("milliseconds")]
        public long Milliseconds { get; set; }
    }
}
